title: Rústico Pesca
description: Dicas de pesca, equipamentos testados e links confiáveis da Shopee, Mercado Livre e AliExpress.
url: https://gustavopinho.github.io
baseurl: /rusticopesca
lang: pt-BR

markdown: kramdown
theme: null

plugins:
  - jekyll-sitemap
